[package]
name = "TestRust"
version = "0.2.0"
authors = ["iwek <miwanczuk7@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.34.2", features = ["bundled", "static-link", "image"] }
gl = "0.6.0"
image = "0.23.14"
glam = "0.17.3"

[build-dependencies]
walkdir = "2.3.2"